import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import AskTejas from "../components/AskTejas";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// AskTejas is a Client Component; importing directly is supported in App Router.

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Script src={`https://www.googletagmanager.com/gtag/js?id=G-PC5SW294RY`} strategy="afterInteractive" />
        <Script id="gtag-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){window.dataLayer.push(arguments);} 
            gtag('js', new Date());
            gtag('config', 'G-PC5SW294RY', { page_path: window.location.pathname });
          `}
        </Script>
        {children}
        <AskTejas />
      </body>
    </html>
  );
}
